version: '3.0'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.fe
      args:
        VITE_FORUM_BACKEND_SERVER: http://localhost:8080
    image: sez54321/mse_2024_sezen_fe:latest
    container_name: frontend
    ports:
      - "8079:8079"
  backend: 
    build: 
      context: .
      dockerfile: Dockerfile.be
    image: sez54321/mse_2024_sezen_be:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: