name: Build and test react app

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Open client folder
        run: cd ./client

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run dev

      - name: Run Cypress tests
        run: npm run cy:run
