name: Build and Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: sez54321/mse_2024_sezen_be:${{ github.event.release.tag_name }}
          context: .
          file: ./Dockerfile.be

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: sez54321/mse_2024_sezen_fe:${{ github.event.release.tag_name }}
          context: .
          file: ./Dockerfile.fe

      - name: Log out of Docker Hub
        if: always()
        run: docker logout
